name = "convert-to-pinyin"
main = "worker.js"
compatibility_date = "2024-01-01"
assets = { directory = "./dist" }

# KV 命名空间绑定
[[kv_namespaces]]
binding = "CONVERT_PINYIN_FAVORITES_KV"
id = "7b4a0e242ab74e569e9c460c5b363d0f"

# 构建配置
[build]
command = "npm run build"

# 环境变量（如果需要）
[vars]
# SOME_VAR = "value"
